path_tracking_controller:
  controller_frequency: 20.0
  controller_plugin: "cmpf_decoupled_controller/DecoupledController"
  DecoupledController:
    longitudinal_controller_plugin: "cmpf_decoupled_controller/PID"
    lateral_controller_plugin: "cmpf_decoupled_controller/PurePursuit"

route_planner:
  publish_route: true
  route_publish_frequency: 10.0